### ISSUE TITLE
GraphQL 2.0 compatible but dependencies too restrictive to use

### ISSUE THREAD

**Issue by lostboy** [TrueCar/graphql-decorate#22]
I think with the last few commits this is now graphql ruby 2 compatible but the gemspec still restricts it to < 2. Can we lift that restriction now?

**Comment by benrbrook** [comment]
Yes, that restriction should be removed. I'll try and get a PR up soon for that.

**Comment by benrbrook** [comment]
I'm seeing some broken behavior when running the gem's specs against `graphql` versions `>= 2`. To support version 2 of the `graphql` gem we might have to make it a hard requirement for future releases.
